---

version: 1
update_configs:
  - package_manager: "go:modules"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"
    directory: "/api"
    update_schedule: "weekly"
    commit_message:
      prefix: "chore"
      include_scope: true
  - package_manager: "javascript"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"
    directory: "/front"
    update_schedule: "weekly"
    commit_message:
      prefix: "chore"
      include_scope: true
